export const SET_DEPARTMENT = 'SET_DEPARTMENT';

export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';

export const SET_CATEGORY = 'SET_CATEGORY';

export const SET_CATEGORIES = 'SET_CATEGORIES';

export const SET_SHIRTS = 'SET_SHIRTS';

export const SET_CURRENT_SHIRT = 'SET_CURRENT_SHIRT';

export const SET_CART_ITEMS = 'SET_CART_ITEMS';

export const SET_PREPARED_ITEMS = 'SET_PREPARED_ITEMS';

export const SET_CURRENT_CUSTOMER = 'SET_CURRENT_CUSTOMER';

export const SET_SEARCH_SHIRTS = 'SET_SEARCH_SHIRTS';